"use client"

export interface ReportData {
  studentName: string
  period: { start: Date; end: Date }
  summary: {
    totalProblems: number
    correctAnswers: number
    accuracy: number
    totalTime: number
    averageTimePerProblem: number
    streak: number
    level: number
  }
  topicBreakdown: {
    topic: string
    problems: number
    correct: number
    accuracy: number
    timeSpent: number
  }[]
  dailyActivity: {
    date: string
    problems: number
    time: number
    accuracy: number
  }[]
  strengths: string[]
  weaknesses: string[]
  recommendations: string[]
  achievements: { name: string; date: Date }[]
}

// Generate PDF Report
export async function generatePDFReport(data: ReportData): Promise<Blob> {
  // Create HTML content for PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; }
        h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        h2 { color: #374151; margin-top: 30px; }
        .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 20px 0; }
        .stat { background: #f3f4f6; padding: 20px; border-radius: 8px; text-align: center; }
        .stat-value { font-size: 32px; font-weight: bold; color: #1e40af; }
        .stat-label { color: #6b7280; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #e5e7eb; padding: 12px; text-align: left; }
        th { background: #f3f4f6; font-weight: bold; }
        .progress-bar { height: 8px; background: #e5e7eb; border-radius: 4px; overflow: hidden; }
        .progress-fill { height: 100%; background: #3b82f6; }
        .recommendation { background: #fef3c7; padding: 15px; border-radius: 8px; margin: 10px 0; }
        .strength { color: #059669; }
        .weakness { color: #dc2626; }
        .footer { margin-top: 40px; text-align: center; color: #6b7280; font-size: 12px; }
      </style>
    </head>
    <body>
      <h1>Learning Progress Report</h1>
      <p><strong>Student:</strong> ${data.studentName}</p>
      <p><strong>Period:</strong> ${data.period.start.toLocaleDateString()} - ${data.period.end.toLocaleDateString()}</p>

      <h2>Summary</h2>
      <div class="summary">
        <div class="stat">
          <div class="stat-value">${data.summary.totalProblems}</div>
          <div class="stat-label">Problems Solved</div>
        </div>
        <div class="stat">
          <div class="stat-value">${data.summary.accuracy}%</div>
          <div class="stat-label">Accuracy</div>
        </div>
        <div class="stat">
          <div class="stat-value">${Math.floor(data.summary.totalTime / 60)}h ${data.summary.totalTime % 60}m</div>
          <div class="stat-label">Total Study Time</div>
        </div>
        <div class="stat">
          <div class="stat-value">${data.summary.streak}</div>
          <div class="stat-label">Day Streak</div>
        </div>
        <div class="stat">
          <div class="stat-value">Lv. ${data.summary.level}</div>
          <div class="stat-label">Current Level</div>
        </div>
        <div class="stat">
          <div class="stat-value">${data.summary.averageTimePerProblem}s</div>
          <div class="stat-label">Avg. Time/Problem</div>
        </div>
      </div>

      <h2>Performance by Topic</h2>
      <table>
        <tr>
          <th>Topic</th>
          <th>Problems</th>
          <th>Correct</th>
          <th>Accuracy</th>
          <th>Time Spent</th>
        </tr>
        ${data.topicBreakdown.map(t => `
          <tr>
            <td>${t.topic}</td>
            <td>${t.problems}</td>
            <td>${t.correct}</td>
            <td>
              <div class="progress-bar">
                <div class="progress-fill" style="width: ${t.accuracy}%"></div>
              </div>
              ${t.accuracy}%
            </td>
            <td>${t.timeSpent} min</td>
          </tr>
        `).join('')}
      </table>

      <h2>Strengths</h2>
      <ul>
        ${data.strengths.map(s => `<li class="strength">✓ ${s}</li>`).join('')}
      </ul>

      <h2>Areas for Improvement</h2>
      <ul>
        ${data.weaknesses.map(w => `<li class="weakness">• ${w}</li>`).join('')}
      </ul>

      <h2>Recommendations</h2>
      ${data.recommendations.map(r => `<div class="recommendation">💡 ${r}</div>`).join('')}

      <h2>Achievements</h2>
      <ul>
        ${data.achievements.map(a => `<li>🏆 ${a.name} - ${a.date.toLocaleDateString()}</li>`).join('')}
      </ul>

      <div class="footer">
        <p>Generated by MathGPT Clone on ${new Date().toLocaleDateString()}</p>
      </div>
    </body>
    </html>
  `

  // Return as HTML blob (in production, use a PDF library)
  return new Blob([htmlContent], { type: "text/html" })
}

// Generate Excel Report
export async function generateExcelReport(data: ReportData): Promise<Blob> {
  // CSV format for Excel compatibility
  let csv = "Learning Progress Report\n\n"

  // Summary section
  csv += "Summary\n"
  csv += "Metric,Value\n"
  csv += `Student Name,${data.studentName}\n`
  csv += `Period Start,${data.period.start.toLocaleDateString()}\n`
  csv += `Period End,${data.period.end.toLocaleDateString()}\n`
  csv += `Total Problems,${data.summary.totalProblems}\n`
  csv += `Correct Answers,${data.summary.correctAnswers}\n`
  csv += `Accuracy,${data.summary.accuracy}%\n`
  csv += `Total Time (min),${data.summary.totalTime}\n`
  csv += `Average Time/Problem (s),${data.summary.averageTimePerProblem}\n`
  csv += `Current Streak,${data.summary.streak}\n`
  csv += `Level,${data.summary.level}\n`
  csv += "\n"

  // Topic breakdown
  csv += "Topic Performance\n"
  csv += "Topic,Problems,Correct,Accuracy,Time Spent (min)\n"
  data.topicBreakdown.forEach((t) => {
    csv += `${t.topic},${t.problems},${t.correct},${t.accuracy}%,${t.timeSpent}\n`
  })
  csv += "\n"

  // Daily activity
  csv += "Daily Activity\n"
  csv += "Date,Problems,Time (min),Accuracy\n"
  data.dailyActivity.forEach((d) => {
    csv += `${d.date},${d.problems},${d.time},${d.accuracy}%\n`
  })
  csv += "\n"

  // Strengths and weaknesses
  csv += "Strengths\n"
  data.strengths.forEach((s) => {
    csv += `${s}\n`
  })
  csv += "\n"

  csv += "Areas for Improvement\n"
  data.weaknesses.forEach((w) => {
    csv += `${w}\n`
  })
  csv += "\n"

  // Recommendations
  csv += "Recommendations\n"
  data.recommendations.forEach((r) => {
    csv += `${r}\n`
  })
  csv += "\n"

  // Achievements
  csv += "Achievements\n"
  csv += "Achievement,Date\n"
  data.achievements.forEach((a) => {
    csv += `${a.name},${a.date.toLocaleDateString()}\n`
  })

  return new Blob([csv], { type: "text/csv" })
}

// Generate JSON Report
export function generateJSONReport(data: ReportData): Blob {
  return new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })
}

// Download helper
export function downloadReport(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// Generate sample report data
export function generateSampleReportData(studentName: string): ReportData {
  return {
    studentName,
    period: {
      start: new Date(Date.now() - 30 * 86400000),
      end: new Date(),
    },
    summary: {
      totalProblems: 347,
      correctAnswers: 289,
      accuracy: 83,
      totalTime: 1250,
      averageTimePerProblem: 216,
      streak: 12,
      level: 7,
    },
    topicBreakdown: [
      { topic: "Algebra", problems: 87, correct: 80, accuracy: 92, timeSpent: 290 },
      { topic: "Calculus", problems: 65, correct: 51, accuracy: 78, timeSpent: 320 },
      { topic: "Geometry", problems: 54, correct: 46, accuracy: 85, timeSpent: 210 },
      { topic: "Trigonometry", problems: 43, correct: 31, accuracy: 72, timeSpent: 230 },
      { topic: "Statistics", problems: 38, correct: 33, accuracy: 87, timeSpent: 150 },
    ],
    dailyActivity: Array.from({ length: 30 }, (_, i) => ({
      date: new Date(Date.now() - (29 - i) * 86400000).toLocaleDateString(),
      problems: Math.floor(Math.random() * 20) + 5,
      time: Math.floor(Math.random() * 60) + 15,
      accuracy: Math.floor(Math.random() * 30) + 70,
    })),
    strengths: [
      "Strong performance in Algebra with 92% accuracy",
      "Consistent daily practice with 12-day streak",
      "Quick problem-solving in Statistics",
    ],
    weaknesses: [
      "Trigonometry accuracy below 75%",
      "Longer than average time on Calculus problems",
      "Some inconsistency in Geometry performance",
    ],
    recommendations: [
      "Focus on practicing trigonometric identities and their applications",
      "Review fundamental calculus concepts, especially integration techniques",
      "Try more challenging Algebra problems to maintain momentum",
      "Consider joining study groups for collaborative learning",
    ],
    achievements: [
      { name: "First 100 Problems", date: new Date(Date.now() - 20 * 86400000) },
      { name: "Week Streak", date: new Date(Date.now() - 5 * 86400000) },
      { name: "Perfect Score Session", date: new Date(Date.now() - 3 * 86400000) },
      { name: "Level 7 Reached", date: new Date(Date.now() - 1 * 86400000) },
    ],
  }
}
